
[General]
ID=0
Name=SEC1
HostIP=127.0.0.1
WorkCueSheetPath=D:\Schedule
LoadCueSheetPath=C:\Program Files\Gemiso\SEC\CueSheet\Load
SaveCueSheetPath=C:\Program Files\Gemiso\SEC\CueSheet\Save
LogPath=C:\Program Files\Gemiso\SEC\Log
LogExt=SEC.log

[Database]
Name=TEST
DriverType=ORACLE
ServerName=TEST
UserID=TEST
Password=TEST

[SEC]
SysInPort=9012
SysCheckTimeout=00:00:01:00
SysCheckInterval=00:00:01:00
SysLogInPortEnabled=False
SysLogPath=C:\Program Files\Gemiso\SEC\SECLog
SysLogExt=SysSEC.log

NotifyPort=9000
InPort=9002
OutPort=9001
CrossPort=9003
CommandTimeout=00:00:01:00
NumCrossCheck=3
CrossCheckInterval=00:00:01:00
LogNotifyPortEnabled=False
LogInPortEnabled=False
LogOutPortEnabled=False
LogPath=C:\Program Files\Gemiso\SEC\SECLog
LogExt=SEC.log

NumSEC=1
SEC1=0,SEC1,127.0.0.1,1
#SEC2=1,SEC2,192.168.1.115,0


[MCC]
Use=False
SysInPort=7012
SysOutPort=7011
SysCheckTimeout=00:00:01:00
SysCheckInterval=00:00:01:00
SysLogInPortEnabled=False
SysLogOutPortEnabled=False
SysLogPath=C:\Program Files\Gemiso\SEC\MCCLog
SysLogExt=SysMCC.log

NotifyPort=7000
InPort=7002
OutPort=7001
CommandTimeout=00:00:01:00
LogNotifyPortEnabled=True
LogInPortEnabled=False
LogOutPortEnabled=False
LogPath=C:\Program Files\Gemiso\SEC\MCCLog
LogExt=MCC.log
NumMCC=1
MCC1=0,MCC1,127.0.0.1,1,1
#MCC2=1,MCC2,10.40.10.32,0,0


[DCS]
SysInPort=8012
SysOutPort=8011
SysCheckTimeout=00:00:01:00
SysCheckInterval=00:00:01:00
SysLogInPortEnabled=False
SysLogOutPortEnabled=False
SysLogPath=C:\Program Files\Gemiso\SEC\DCSLog
SysLogExt=SysDCS.log

NotifyPort=8000
InPort=8002
OutPort=8001
CommandTimeout=00:00:02:00
LogNotifyPortEnabled=False
LogInPortEnabled=False
LogOutPortEnabled=False
LogPath=C:\Program Files\Gemiso\SEC\DCSLog
LogExt=DCS.log

[MCS]
NumMCS=4
MCS1=0,SKB_C1_MSW1
MCS2=0,SKB_C1_MSW1_B
MCS3=1,SKB_C2_MSW1
MCS4=1,SKB_C2_MSW1_B



[TimeParameter]
OnAirEventControlInterval=
OnAirCheckDeviceStatusInterval=00:00:01:00
OnAirLoopSleepTime=00:00:00:04
OnAirEnqueueInterval=00:00:05:00
OnAirErrorRecoveryInterval=00:00:10:00
OnAirAutoSaveCuesheetInterval=00:01:00:00
OnAirRefreshGridInterval=00:00:01:00
OnAirChannelDataUpdateInterval=00:00:01:00
MonitorCheckChannelDataInterval=00:00:01:00
MonitorLoopSleepTime=00:00:00:04
AutoIncreaseDurationAmount=00:02:00:00
AutoIncreaseDurationBefore=00:00:20:00
FindReplaceUpdateInterval=00:00:10:00
SourceExchangeUpdateInterval=00:00:10:00
StandardTimeCorrection=00:00:00:00
ForceRefreshEventQueueInterval=00:30:00:00
ForceRefreshEventQueueMinDur=00:01:00:00
RequestUpdateInterval=00:00:10:00
PerformUpdateInterval=00:00:10:00
ProbeManagerInterval=00:00:10:00
NextEventInputBefore=00:00:20:00

MediaCheckInterval=00:20:00:00
MediaCheckTime=02:00:00:00

BlankCheckInterval=24:00:00:00
BlankCheckTime=00:00:00:00

DeadlineHour=24



[ThresholdTime]
OnAirCheckDeviceTimeout=00:00:10:00

OnAirLockTime=00:00:30:00
EditLockTime=00:00:15:00
DeviceControlLockTime=00:01:00:00
CueAllLockTime=00:00:30:00


SetNextLockTime=00:00:10:00
HoldLockTime=00:00:10:00
EnqueueLockTime=00:00:05:00

BreakLockTime=00:00:10:00

MinDuration=00:00:05:00
MaxDuration=23:59:59:00
MinTransitionInterval=00:00:05:00
--MinTakeInterval=00:00:05:00

OnAirEventTransitionThreshold=00:00:03:00

[Option]
TimelineZoomType=6
TimelineSpace=100
TimelineSpaceInterval=100
TimelineFrameRateType=29.97 DF
TimelineOnairIconFileName=C:\Program Files\Gemiso\SEC\Images\TimelineOnairIcon.png
TimelineNextIconFileName=C:\Program Files\Gemiso\SEC\Images\TimelineNextIcon.png
TimelineNormalIconFileName=C:\Program Files\Gemiso\SEC\Images\TimelineNormalIcon.png

ChannelTimelineHeight = 200

AutoLoadCuesheet=True
AutoLoadCuesheetInterval=00:00:30:00
AutoEjectCuesheet=False
AutoEjectCuesheetInterval=00:10:00:00
MaxInputEventCount=50
MediaCheckInterval=00:20:00:00
MediaCheckTime=02:00:00:00
OnAirEventHighlight=True
OnAirEventFixedRow=2

OnAirCheckDeviceNotify=True

OnAirCheckDeviceAlarm=False
OnAirCheckDeviceAlarmFileName=C:\Program Files\Gemiso\SEC\wav\sms-alert-2-daniel_simon.wav
OnAirCheckDeviceAlarmDuration=00:00:10:00
OnAirCheckDeviceAlarmInterval=00:00:01:00

OnAirCheckEventAlarm=False
OnAirCheckEventAlarmFileName=C:\Program Files\Gemiso\SEC\wav\sms-alert-4-daniel_simon.wav
OnAirCheckEventAlarmDuration=00:00:10:00
OnAirCheckEventAlarmInterval=00:00:01:00


MediaCheckAlarm=False
MediaCheckAlarmFileName=C:\Program Files\Gemiso\SEC\wav\sms-alert-3-daniel_simon.wav
MediaCheckAlarmDuration=00:00:10:00
MediaCheckAlarmInterval=00:00:01:00

BlankCheckAlarm=False
BlankCheckAlarmFileName=C:\Program Files\Gemiso\SEC\wav\sms-alert-1-daniel_simon.wav
BlankCheckAlarmDuration=00:00:10:00
BlankCheckAlarmInterval=00:00:01:00
TimelineZoomType=5

[ProgramType]
NumType=11
Type1=0,MAIN,79,119,155
Type2=1,CM,199,195,70
Type3=2,NEXT,128,128,192
Type4=3,PRETITLE,0,255,64
Type5=4,POSTTITLE,128,128,255
Type6=5,ID,9,199,118
Type7=6,PROMO,255,128,128
Type8=7,FILLER,255,0,128
Type9=8,LINEUP,128,0,255
Type10=9,RATE,128,128,128
Type11=10,CG,255,128,0

[OldGradeType]
TypeNum=7
Type1= Ϲ 
Type2=12   ̻ 
Type3=15   ̻ 
Type4=19   ̻ 
Type5=19   ̻ (    )
Type6=  ۺҰ 
Type7=  ޾   

[EventColumnDefault]
StartMode=1
Input=1
OutputBkgnd=3
OutputKeyer=0
Source=PLUS2_DEC1
DurationTC=00:00:00:00
InTC=00:00:00:00
OutTC=00:00:00:00
TransitionType=0
TransitionRate=0
ProgramType=0
FinishAction=1

[EventColumnDefault_bak]
StartMode=1
Input=0
Output=3
Control=0
Source=DEC5
VideoType=0
AudioType=4
Timecode=00:00:00:00
TransitionType=0
TransitionRate=0
ProgramType=0
OldGradeType=0
FinishAction=1

[Grid]
OnAirGridRatio=0.431451612903226
